### ISSUE TITLE
Populate a CI_SERVICE_alias from the worker side for each service to allow easy reference from .gitlab-ci.yml

### ISSUE THREAD

**Issue by pauldoomgov** [GSA-TTS/gitlab-runner-cloudgov#7]
With #5 we added service workers but calculating the hostname inside gitlab-ci.yml requires this mess:

~~~yaml
variables:
  SERVICE_PREFIX: "glrw-r$CI_RUNNER_ID-p$CI_PROJECT_ID-c$CI_CONCURRENT_PROJECT_ID-j$CI_JOB_ID-svc-"
~~~

That is ugly! It would be nice to have a variable like `CI_SERVICE_PREFIX` available in all jobs as a preset environment variable so steps could use it to find services, and CI versions of config files could reference it directly.

Update instead of a prefix, how about generating a FQDN? Yeah. Let's do that.

**Comment by zjrgov** [comment]
Bonus item: do we want to do anything extra for URLs? i.e. `http://${service_prefix}website.apps.internal`?

**Comment by pauldoomgov** [comment]
I tried a few approaches to this. For posterity, here is one I abandoned that may come in handy later if we need to have a persistent variable set on the manager side that is visible to all scripts (prepare.sh, run.sh, etc):

`config.sh`:
~~~sh
#!/usr/bin/env bash
#
# Generate custom configuration JSON - https://docs.gitlab.com/runner/executors/custom.html#config
# STDOUT needs to be well formed JSON or this gets ignored.

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${currentDir}/base.sh" # Get variables from base.

SERVICE_PREFIX="${CONTAINER_ID}-svc-"

CUSTOM_ENVIRONMENT=()

if [ -n "$CUSTOM_ENV_CI_JOB_SERVICES" ]; then
    CUSTOM_ENVIRONMENT+=$(echo "$CUSTOM_ENV_CI_JOB_SERVICES" | jq ".[] | {(\"CUSTOM_ENV_SERVICE_\" + .alias): (\"${SERVICE_PREFIX}\" + .alias + \".apps.internal\")}")
fi

if [[ -z ${CUSTOM_ENVIRONMENT[@]} ]]; then
    exit 0
fi

echo "[cf-driver] Adding configuration from config.sh" 1>&2

cat << EOS
{
  "job_env" : $( echo ${CUSTOM_ENVIRONMENT[@]} | jq -s 'add' )
}
EOS
~~~

To use this you also need to setup use of a config_exec step by setting the `CUSTOM_CONFIG_EXEC` variable to `"/home/vcap/app/cf-driver/config.sh"` in `/manifest.yml`.

If you use this read the linked documentation carefully. It does not populate variables into the jobs.
